import UIPlugin from 'phaser3-rex-plugins/templates/ui/ui-plugin';
import { Scene } from 'phaser';
import TextBox from 'phaser3-rex-plugins/templates/ui/textbox/TextBox';
export declare class Game extends Scene {
    camera: Phaser.Cameras.Scene2D.Camera;
    background: Phaser.GameObjects.Image;
    gameText: Phaser.GameObjects.Text;
    rexUI: UIPlugin;
    tutorialTextBox: TextBox;
    realLogGroup: Phaser.Physics.Arcade.StaticGroup;
    realLog: Phaser.Physics.Arcade.Sprite;
    waterProgressBar: Phaser.GameObjects.Shape;
    waterFillProgressBar: Phaser.GameObjects.Shape;
    isTextDone: boolean;
    hasRun: boolean;
    isLogFull: boolean;
    isLogFullHasRun: boolean;
    isMushroomDone: boolean;
    isCurrentBatchHarvested: boolean;
    waterDropListener: Phaser.Events.EventEmitter;
    tutorialTimerText: Phaser.GameObjects.Text;
    tutorialTimerHarvest: Phaser.Time.TimerEvent;
    mushroomSprite: Phaser.Physics.Arcade.Sprite;
    mushroomTween: Phaser.Tweens.Tween | null;
    mushroomCurrency: number;
    mushroomCurrencyText: Phaser.GameObjects.Text;
    numberOfMushrooms: number;
    mushroomGroup: Phaser.Physics.Arcade.StaticGroup;
    count: number;
    shopContainer: Phaser.GameObjects.Container;
    coins: number;
    coinsText: Phaser.GameObjects.Text;
    shopScene: Phaser.Scene | null;
    cardShopScene: Phaser.Scene | null;
    exchangeShopIcon: Phaser.GameObjects.Image;
    cardShopIcon: Phaser.GameObjects.Image;
    inventoryIcon: Phaser.GameObjects.Image;
    inventoryScene: Phaser.Scene | null;
    userInventory: string[];
    themeSong: Phaser.Sound.WebAudioSound;
    pop1: Phaser.Sound.BaseSound;
    pop2: Phaser.Sound.BaseSound;
    pop3: Phaser.Sound.BaseSound;
    pop4: Phaser.Sound.BaseSound;
    waterdropSound: Phaser.Sound.BaseSound;
    muteButton: Phaser.GameObjects.Image;
    mushroomGrowSound: Phaser.Sound.BaseSound;
    userFinishTutorial: boolean;
    constructor();
    createTextBox(): TextBox;
    create(data: {
        fadeIn: boolean;
        coins: number;
        mushrooms: number;
        cards: string[];
        tutorialFinished: boolean;
    }): void;
    createShopScene(func: any): void;
    update(): void;
    startWatering(): void;
    startHarvesting(): void;
    createMushrooms(): Phaser.Physics.Arcade.Sprite;
    mushroomGrowth(): void;
    changeScene(): void;
    playRandom(): void;
}
